<?php

namespace Panda86\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Request_EmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Request_EmployeeRepository extends EntityRepository
{
}
